### ISSUE TITLE
UI: add a descriptive title.

### ISSUE THREAD

**Issue by vv-monsalve** [Lorp/fencer#18]
So it is easy to identify and get back to that tab. Currently it only says "Home"

<img width="439" alt="Screen Shot 2024-06-06 at 20 45 17" src="https://github.com/Lorp/fencer/assets/48698976/4a75a982-a0af-45df-9ee3-bf0e9fc09dab">

**Comment by Lorp** [comment]
Thanks for this, fixed now.
