### ISSUE TITLE
Reset UI doesn't work atm

### ISSUE THREAD

**Issue by davelab6** [Lorp/fencer#29]
Reset UI doesn't work atm for me in macOS Chrome

**Comment by Lorp** [comment]
Oops, that was a dead button. It is now implemented in d13955118d268210c11deb689572fbc91dc18271

If you have a better proposal for the initial window arrangement that it should reset to, then please inspect the `class="window"` elements and edit their left, top, width, height, let me know and I’ll fix in source.
 
![Screenshot 2024-08-21 at 21 54 36](https://github.com/user-attachments/assets/f9c36c95-0576-4e25-8440-c34ba46c5f74)
